syntax = "proto3";

package auth;

option go_package = "bank_proto_microservice/proto/auth;authpb";

service AuthService {
  rpc Register(RegisterRequest) returns (RegisterResponse);
  rpc Login(LoginRequest) returns (LoginResponse);
  rpc DeleteUser(DeleteUserRequest) returns (DeleteUserResponse);
}

message RegisterRequest {
  string name = 1;
  string password = 2;
}

message RegisterResponse {
  string user_id = 1;
  string name = 2;
  string created_at = 3;
}

message LoginRequest {
  string name = 1;
  string password = 2;
}

message LoginResponse {
  string token = 1;
  string user_id = 2;
  string name = 3;
  string expires_in = 4;
}

message DeleteUserRequest {
  string user_id = 1;
}

message DeleteUserResponse {
  bool success = 1;
  string message = 2;
}